### ISSUE TITLE
Input files cannot be fastq.gz?

### ISSUE THREAD

**Issue by nascimento-jean** [niemasd/ViralConsensus#5]
Good afternoon.

My name is Jean Nascimento and I would like to congratulate you on the development of the ViralConsensus pipeline.
I would love to use it in my analyses, however I am having difficulties with the input files.
I can't use fastq.gz files?
I saw that in the Usage section, it says that the input files must be CRAM, BAM and, SAM files. Could you explain me better?
If I want to use the fastq.gz files directly, could you help me on how I can do that?

Thanks in advance.

**Comment by niemasd** [comment]
Thanks for reaching out! ViralConsensus only accepts mapped reads as its input, so you would need to first map them to your reference genome before running ViralConsensus (using a read mapper like [Minimap2](https://github.com/lh3/minimap2) or similar): ViralConsensus cannot take unmapped reads (a FASTQ or FASTQ.GZ) as input directly.

You can either map and save as a SAM/BAM/CRAM file to then feed into ViralConsensus, or you can [map the reads and pipe the output of the read mapper directly into ViralConsensus](https://github.com/niemasd/ViralConsensus#piping-from-read-mapper)

**Comment by niemasd** [comment]
I'll go ahead and close this GitHub Issue, as it seems to be resolved, but please feel free to reopen it if you have follow-up questions
