### ISSUE TITLE
Add to conda

### ISSUE THREAD

**Issue by austinreidmanny** [niemasd/ViralConsensus#8]
It would be immensely helpful if this tool could be installed using `conda` so it could be installed on the fly using Nextflow.

**Comment by niemasd** [comment]
Ah, that's a great idea! Do you happen to have a link to a guide or something for adding tools to conda? I'll look into it shortly if not, but any pointers would be helpful

**Comment by austinreidmanny** [comment]
Sadly, I have no idea! I've only retrieved packages from Honda, I've never uploaded any.

**Comment by niemasd** [comment]
No worries! I'll look into it 😄 Thanks!

**Comment by niemasd** [comment]
Initial attempt to add it to bioconda started; just debugging now, and hopefully it'll be added soon!

https://github.com/bioconda/bioconda-recipes/pull/43322

**Comment by niemasd** [comment]
Finally got it passing the bioconda integration tests, so hopefully it'll be added soon!

https://github.com/bioconda/bioconda-recipes/pull/43322#issuecomment-1740376767

**Comment by niemasd** [comment]
@austinreidmanny ViralConsensus has officially been merged into Bioconda!

https://github.com/bioconda/bioconda-recipes/commit/71a8adb88a3e1c9b69ea540103ae992074b15f0f

So some time in the next day or so (the documentation says ~30 min), you should be able to install it with `conda install viral_consensus`. Can you try it and let me know if it works for you?

**Comment by niemasd** [comment]
Looks like it's live!

https://anaconda.org/bioconda/viral_consensus
